"""Add mbti_type column to participant

Revision ID: 22e5c54eb71a
Revises: 997fa7674c16
Create Date: 2024-09-12 18:32:14.797919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e5c54eb71a'
down_revision = '997fa7674c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_visitor')
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbti_type', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('mbti_type')

    op.create_table('_alembic_tmp_visitor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_visit', sa.DATETIME(), nullable=True),
    sa.Column('last_visit', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
