"""Description of changes

Revision ID: 997fa7674c16
Revises: 3270510e7f92
Create Date: 2024-09-09 23:57:38.971723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997fa7674c16'
down_revision = '3270510e7f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False))
        batch_op.add_column(sa.Column('user_agent', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
